name = "book-directory"
main = "app.js"
compatibility_date = "2025-07-14"

[vars]
DB_URI = "mongodb+srv://azka:QwQ1JM5hiYbUEHdZ@cluster0.4cs5onl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"